function p=jointPositions(bodyAngles,bodyPos,jointAngles,wBodyInput,lenBodyInput,distalLen,proximalLen,legNo)

bodyX=bodyPos(1);bodyY=bodyPos(2);bodyZ=bodyPos(3);
thX=bodyAngles(1);thY=bodyPos(2);thZ=bodyPos(3);

th11 = jointAngles(1);
th12 = jointAngles(2);
th13 = jointAngles(3);
WBody = wBodyInput*sqrt(2)*sin(1/2*pi*(legNo - 1) + pi/4) ;
LBody = lenBodyInput*sqrt(2)*cos(1/2*pi*(legNo - 1) + pi/4) ;

p1=[bodyX,bodyY,bodyZ];

p2=[bodyX + (cos(thY)*(LBody*cos(thZ) - WBody*sin(thZ)))/2,...
    (2*bodyY + cos(thX)*(WBody*cos(thZ) + LBody*sin(thZ)) + ...
    sin(thX)*sin(thY)*(LBody*cos(thZ) - WBody*sin(thZ)))/2,...
    (2*bodyZ + sin(thX)*(WBody*cos(thZ) + LBody*sin(thZ)) + ...
    cos(thX)*sin(thY)*(-(LBody*cos(thZ)) + WBody*sin(thZ)))/2];

p3=[bodyX - proximalLen*sin(th12)*sin(thY) + (cos(thY)*(LBody*cos(thZ) +...
    2*proximalLen*cos(th12)*cos(th11 + thZ) - WBody*sin(thZ)))/2,...
    bodyY + proximalLen*cos(thY)*sin(th12)*sin(thX) + ...
    (sin(thX)*sin(thY)*(LBody*cos(thZ) + ...
    2*proximalLen*cos(th12)*cos(th11 + thZ) - WBody*sin(thZ)) + ...
    cos(thX)*(WBody*cos(thZ) + LBody*sin(thZ) + ...
    2*proximalLen*cos(th12)*sin(th11 + thZ)))/2,...
    (2*bodyZ - cos(thX)*(2*proximalLen*cos(thY)*sin(th12) + ...
    sin(thY)*(LBody*cos(thZ) + ...
    2*proximalLen*cos(th12)*cos(th11 + thZ) - WBody*sin(thZ))) + ...
    sin(thX)*(WBody*cos(thZ) + LBody*sin(thZ) + ...
    2*proximalLen*cos(th12)*sin(th11 + thZ)))/2];

p4=[bodyX - (proximalLen*sin(th12) + ...
    distalLen*sin(th12 + th13))*sin(thY) + (cos(thY)*(LBody*cos(thZ) + ...
    2*(proximalLen*cos(th12) + ...
    distalLen*cos(th12 + th13))*cos(th11 + thZ) - WBody*sin(thZ)))/2,...
    bodyY + cos(thY)*(proximalLen*sin(th12) + ...
    distalLen*sin(th12 + th13))*sin(thX) + ...
    (sin(thX)*sin(thY)*(LBody*cos(thZ) + 2*(proximalLen*cos(th12) +...
    distalLen*cos(th12 + th13))*cos(th11 + thZ) - WBody*sin(thZ)) + ...
    cos(thX)*(WBody*cos(thZ) + LBody*sin(thZ) + ...
    2*(proximalLen*cos(th12) + ...
    distalLen*cos(th12 + th13))*sin(th11 + thZ)))/2,...
    bodyZ - (cos(thX)*(2*cos(thY)*(proximalLen*sin(th12) + ...
    distalLen*sin(th12 + th13)) + sin(thY)*(LBody*cos(thZ) + ...
    2*(proximalLen*cos(th12) + ...
    distalLen*cos(th12 + th13))*cos(th11 + thZ) - WBody*sin(thZ))))/2 + ...
    (sin(thX)*(WBody*cos(thZ) + LBody*sin(thZ) + ...
    2*(proximalLen*cos(th12) + ...
    distalLen*cos(th12 + th13))*sin(th11 + thZ)))/2];

p=[p1;p2;p3;p4];

end